/*
 * generated by Xtext
 */
package org.search.niem.uml.papyrus.textedit.property.xtext.scoping

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
class NIEMUmlPropertyScopeProvider extends org.eclipse.papyrus.uml.textedit.property.xtext.scoping.UmlPropertyScopeProvider {

}
