/*
 * generated by Xtext
 */
package org.search.niem.uml.papyrus.textedit.property.xtext.ui.contentassist

import org.search.niem.uml.papyrus.textedit.property.xtext.ui.contentassist.AbstractNIEMUmlPropertyProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class NIEMUmlPropertyProposalProvider extends AbstractNIEMUmlPropertyProposalProvider {
}
