/*
 * generated by Xtext
 */
package org.search.niem.uml.papyrus.textedit.property.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.search.niem.uml.papyrus.textedit.property.xtext.ui.internal.NIEMUmlPropertyActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NIEMUmlPropertyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return NIEMUmlPropertyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return NIEMUmlPropertyActivator.getInstance().getInjector(NIEMUmlPropertyActivator.ORG_SEARCH_NIEM_UML_PAPYRUS_TEXTEDIT_PROPERTY_XTEXT_NIEMUMLPROPERTY);
	}
	
}
