/*
 * generated by Xtext
 */
package org.search.niem.uml.papyrus.textedit.property.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NIEMUmlPropertyUiModule extends org.search.niem.uml.papyrus.textedit.property.xtext.ui.AbstractNIEMUmlPropertyUiModule {
	public NIEMUmlPropertyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
