/*
* generated by Xtext
*/
package org.search.niem.uml.papyrus.textedit.property.xtext.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators= {org.eclipse.xtext.validation.ImportUriValidator.class, org.eclipse.xtext.validation.NamesAreUniqueValidator.class})
public class AbstractNIEMUmlPropertyJavaValidator extends org.eclipse.papyrus.uml.textedit.property.xtext.validation.UmlPropertyJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.search.niem.uml.papyrus.textedit.property.xtext.niemUmlProperty.NiemUmlPropertyPackage.eINSTANCE);
		return result;
	}

}
