/*
* generated by Xtext
*/
package org.search.niem.uml.papyrus.textedit.property.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class NIEMUmlPropertyAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/search/niem/uml/papyrus/textedit/property/xtext/parser/antlr/internal/InternalNIEMUmlProperty.tokens");
	}
}
