/*
* generated by Xtext
*/
package org.search.niem.uml.papyrus.textedit.property.xtext.ui.outline

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
class NIEMUmlPropertyOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {
	
}
