/*
* generated by Xtext
*/
package org.search.niem.uml.papyrus.textedit.property.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class NIEMUmlPropertyStandaloneSetup extends NIEMUmlPropertyStandaloneSetupGenerated{

	public static void doSetup() {
		new NIEMUmlPropertyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

