/*
 * generated by Xtext
 */
package org.search.niem.uml.papyrus.textedit.property.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NIEMUmlPropertyRuntimeModule extends org.search.niem.uml.papyrus.textedit.property.xtext.AbstractNIEMUmlPropertyRuntimeModule {

}
