/*
* generated by Xtext
*/
package org.search.niem.uml.papyrus.textedit.property.xtext.validation;

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class NIEMUmlPropertyJavaValidator extends org.search.niem.uml.papyrus.textedit.property.xtext.validation.AbstractNIEMUmlPropertyJavaValidator {

//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital", MyDslPackage.Literals.GREETING__NAME);
//		}
//	}
}
